snowflake-to-kafka-cluster:
    container_name: snowflake-stream-kafka
    image: landoop/fast-data-dev
    environment:
      ADV_HOST: 127.0.0.1         
      RUNTESTS: 0                 
    ports:
      - 2181:2181                 
      - 3030:3030                 
      - 8081-8083:8081-8083       
      - 9581-9585:9581-9585       
      - 9092:9092                 
    volumes:
      # This can be any path in your system. Be sure to specify absolute
      - C:\Users\pandey\Documents\Documents\Projects\snowflake-kafka:/my-data
